name: dart_functions_collections
description: Academia do Flutter module of functions and collections
version: 1.0.0
repository: https://github.com/alinebrugnolli?tab=repositories

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
